# Generated by Django 5.2.7 on 2025-10-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0004_message_request_to_change_wiki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('wikis', models.ManyToManyField(related_name='tags', to='infrastructure.wiki')),
            ],
        ),
    ]
