# Generated by Django 5.2.7 on 2025-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='redacting',
            field=models.BooleanField(default=True),
        ),
    ]
