# Generated by Django 5.2.7 on 2025-10-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_message_request_to_change_wiki'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
